### ISSUE TITLE
Translated version cannot load saved games from the original version

### ISSUE THREAD

**Issue by erlichg** [adventurebrew/HebrewAdventure#10]
Hey,
So I started playing the game (qfg1vga) and midway I discovered your wonderful translation.
Works like a charm.
However, I can't seem to load saves from before the translation. Is it a know issue?

**Comment by ZvikaZ** [comment]
Thanks.

Yes, it's a known issue. Some of the English strings are stored inside the 'script' game files. Therefore, in order to translate them, the scripts are modified, and we get a new "version" of the game that's incompatible with other versions. So, sadly, save games cannot be shared between translated and original games.

Furthermore, if you'll find some bug in the translation, and I will fix it, there's a good chance that it will render your existing Hebrew save games unloadable in the fixed version.

**Comment by erlichg** [comment]
I see, Thanks for the explanation.
One more question: I was wondering it's possible to use the translated version with dosbox. I tried to do so but does box showed the Hebrew translation in reverse.

**Comment by ZvikaZ** [comment]
Well, you already know the answer :-)

Hebrew (or other right-to-left languages) support need to be in the interpreter that runs the game files. Since Sierra didn't support Hebrew originally, they show the Hebrew text reversed, and left aligned, as if it's an European language.

The first part of translating Sierra games to Hebrew was adding Hebrew support to ScummVM, which is a replacement to the original Sierra interpreter (what you run with DOSBox). Theoretically, it might be possible to add Hebrew support to the original Sierra interpreter (i.e., DOSBox) as well, but it'll be very difficult, and not really worth the effort, since ScummVM runs it very nicely (or maybe even better).

**Comment by erlichg** [comment]
thanks! Loving your translation.
If you need any help with other translations, let me know. Especially interested in the QFG series.

**Comment by ZvikaZ** [comment]
That's great to hear!
I want to emphasize, that we are a team. My part at QFG1 was pretty minor...

Anyway, you're welcome to join our Discord server. That's where you be be more involved and suggest your help.
